import { useState, useRef, useEffect } from 'react';
import { Filter, Plus, Tag, Columns3, ChevronDown, Check, Menu, Download, Upload, Pencil, Trash2 } from 'lucide-react';
import { ReasonAdd } from './ReasonAdd';
import { Pagination } from '../../../components/ui/Pagination';
import { useReason } from '../../../providers/ReasonProvider';
import { REASON_TYPE_OPTIONS } from '../../../types/Reason';
interface Column { key: string; label: string; visible: boolean; }

export function ReasonList() {
  const { data: reasons, meta, isLoading, error, currentPage, setCurrentPage, perPage, setPerPage, searchTerm, setSearchTerm, typeFilter, setTypeFilter, selectedRowKeys, setSelectedRowKeys, handleDeleteWithConfirmation, addDrawerOpen, setAddDrawerOpen, editingItem, setEditingItem, createReasonData, updateReasonData } = useReason();
  const totalPages = meta?.last_page ?? 1; const total = meta?.total ?? 0;
  const [columnsDropdownOpen, setColumnsDropdownOpen] = useState(false); const [moreActionsOpen, setMoreActionsOpen] = useState(false); const [filterOpen, setFilterOpen] = useState(false); const [searchDraft, setSearchDraft] = useState(''); const [typeFilterDraft, setTypeFilterDraft] = useState('');
  const [columns, setColumns] = useState<Column[]>([{ key: 'code', label: 'Code', visible: true }, { key: 'name', label: 'Name', visible: true }, { key: 'type', label: 'Type', visible: true }]);
  const columnsRef = useRef<HTMLDivElement>(null); const moreActionsRef = useRef<HTMLDivElement>(null);
  useEffect(() => { function h(e: MouseEvent) { if (columnsRef.current && !columnsRef.current.contains(e.target as Node)) setColumnsDropdownOpen(false); if (moreActionsRef.current && !moreActionsRef.current.contains(e.target as Node)) setMoreActionsOpen(false); } document.addEventListener('mousedown', h); return () => document.removeEventListener('mousedown', h); }, []);
  const toggleColumn = (key: string) => setColumns(prev => prev.map(col => col.key === key ? { ...col, visible: !col.visible } : col));
  const isColumnVisible = (key: string) => columns.find(c => c.key === key)?.visible ?? true;
  const isCodeVisible = isColumnVisible('code');
  const isNameVisible = isColumnVisible('name');
  const isTypeVisible = isColumnVisible('type');
  const visibleColCount = 2 + (isCodeVisible ? 1 : 0) + (isNameVisible ? 1 : 0) + (isTypeVisible ? 1 : 0);
  const activeFilterCount = (searchTerm ? 1 : 0) + (typeFilter ? 1 : 0);
  const allSelected = reasons.length > 0 && selectedRowKeys.length === reasons.length;
  const handleSelectAll = () => setSelectedRowKeys(allSelected ? [] : reasons.map((c: any) => c.uuid ?? String(c.id)));
  const handleSelectRow = (id: string) => setSelectedRowKeys(selectedRowKeys.includes(id) ? selectedRowKeys.filter(k => k !== id) : [...selectedRowKeys, id]);
  const applySearch = () => { setSearchTerm(searchDraft); setTypeFilter(typeFilterDraft); setCurrentPage(1); };
  const clearSearch = () => { setSearchDraft(''); setTypeFilterDraft(''); setSearchTerm(''); setTypeFilter(''); setCurrentPage(1); setFilterOpen(false); };
  const handleEditClick = (item: any) => { setEditingItem(item); setAddDrawerOpen(true); };
  const handleDrawerClose = () => { setAddDrawerOpen(false); setEditingItem(null); };
  const handleSaved = () => { handleDrawerClose(); };
  const handleReasonEvent = async (event: any) => {
    if (event.eventType === 'ReasonUpdated' && editingItem) {
      await updateReasonData(editingItem.uuid, event.reason);
    } else {
      await createReasonData(event.reason);
    }
    handleSaved();
  };

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 px-6 pb-0 pt-6">
        <div className="flex items-center gap-3"><Tag className="w-6 h-6 text-[var(--text-primary)]" /><div><h1 className="text-2xl font-bold text-[var(--text-primary)]">Reasons</h1><p className="text-[var(--text-secondary)] mt-1">Manage reason types</p></div></div>
        <div className="flex flex-wrap items-center gap-2">
          <button onClick={() => setFilterOpen(prev => !prev)} className={`inline-flex items-center gap-2 px-4 py-2 text-sm font-medium rounded-lg border transition-colors ${filterOpen || activeFilterCount > 0 ? 'bg-primary-50 dark:bg-primary-900/20 border-primary-300 dark:border-primary-700 text-primary-700 dark:text-primary-300' : 'bg-[var(--bg-card)] border-[var(--border-color)] text-[var(--text-primary)] hover:bg-[var(--bg-secondary)]'}`}><Filter className="w-4 h-4" />Filter{activeFilterCount > 0 && <span className="ml-1 px-1.5 py-0.5 text-xs bg-primary-600 text-white rounded-full">{activeFilterCount}</span>}</button>
          <div className="relative" ref={columnsRef}><button onClick={() => setColumnsDropdownOpen(!columnsDropdownOpen)} className="inline-flex items-center gap-2 px-4 py-2 text-sm font-medium bg-[var(--bg-card)] border border-[var(--border-color)] text-[var(--text-primary)] rounded-lg hover:bg-[var(--bg-secondary)] transition-colors"><Columns3 className="w-4 h-4" />Columns<ChevronDown className="w-4 h-4" /></button>{columnsDropdownOpen && (<div className="absolute right-0 mt-2 w-48 bg-[var(--bg-card)] border border-[var(--border-color)] rounded-lg shadow-lg z-20"><div className="py-1">{columns.map(col => (<button key={col.key} onClick={() => toggleColumn(col.key)} className="w-full flex items-center justify-between px-4 py-2 text-sm text-[var(--text-primary)] hover:bg-[var(--bg-secondary)] transition-colors"><span>{col.label}</span>{col.visible && <Check className="w-4 h-4 text-primary-600" />}</button>))}</div></div>)}</div>
          <button onClick={() => { setEditingItem(null); setAddDrawerOpen(true); }} className="inline-flex items-center gap-2 px-4 py-2 text-sm font-medium bg-primary-600 text-white rounded-lg hover:bg-primary-700 transition-colors"><Plus className="w-4 h-4" />Create</button>
          <div className="relative" ref={moreActionsRef}><button onClick={() => setMoreActionsOpen(!moreActionsOpen)} className="inline-flex items-center justify-center p-2 text-sm font-medium bg-[var(--bg-card)] border border-[var(--border-color)] text-[var(--text-primary)] rounded-lg hover:bg-[var(--bg-secondary)] transition-colors"><Menu className="w-5 h-5" /><ChevronDown className="w-4 h-4" /></button>{moreActionsOpen && (<div className="absolute right-0 mt-2 w-40 bg-[var(--bg-card)] border border-[var(--border-color)] rounded-lg shadow-lg z-20"><div className="py-1"><button onClick={() => setMoreActionsOpen(false)} className="w-full flex items-center gap-2 px-4 py-2 text-sm text-[var(--text-primary)] hover:bg-[var(--bg-secondary)] transition-colors"><Download className="w-4 h-4" />Export</button><button onClick={() => setMoreActionsOpen(false)} className="w-full flex items-center gap-2 px-4 py-2 text-sm text-[var(--text-primary)] hover:bg-[var(--bg-secondary)] transition-colors"><Upload className="w-4 h-4" />Import</button></div></div>)}</div>
        </div>
      </div>
      {filterOpen && (<div className="mx-6 mb-2 bg-[var(--bg-card)] border border-[var(--border-color)] rounded-xl px-5 py-4 shadow-sm"><div className="flex flex-wrap items-end gap-3"><div className="flex flex-col gap-1 flex-1 min-w-[200px]"><label className="text-xs font-medium text-[var(--text-secondary)]">Search</label><input type="text" value={searchDraft} onChange={e => setSearchDraft(e.target.value)} onKeyDown={e => e.key === 'Enter' && applySearch()} placeholder="Search…" className="px-3 py-2 text-sm rounded-lg border border-[var(--border-color)] bg-[var(--bg-secondary)] text-[var(--text-primary)] placeholder-[var(--text-muted)] focus:outline-none focus:ring-2 focus:ring-primary-500" /></div><div className="flex flex-col gap-1 flex-1 min-w-[200px]"><label className="text-xs font-medium text-[var(--text-secondary)]">Type</label><select value={typeFilterDraft} onChange={e => setTypeFilterDraft(e.target.value)} className="px-3 py-2 text-sm rounded-lg border border-[var(--border-color)] bg-[var(--bg-secondary)] text-[var(--text-primary)] focus:outline-none focus:ring-2 focus:ring-primary-500"><option value="">All types</option>{REASON_TYPE_OPTIONS.map(option => <option key={option} value={option}>{option}</option>)}</select></div><div className="flex items-end gap-2 pb-0.5"><button onClick={applySearch} className="px-4 py-2 text-sm font-medium bg-primary-600 hover:bg-primary-700 text-white rounded-lg transition-colors">Apply</button><button onClick={clearSearch} className="px-4 py-2 text-sm font-medium bg-[var(--bg-secondary)] hover:bg-[var(--bg-card)] border border-[var(--border-color)] text-[var(--text-primary)] rounded-lg transition-colors">Clear</button></div></div></div>)}
      <div className="bg-[var(--bg-card)] rounded-xl border border-[var(--border-color)] overflow-hidden transition-theme relative min-h-[200px] mx-6">
        {isLoading && (<div className="absolute inset-0 z-10 bg-white/50 dark:bg-black/20 flex items-center justify-center"><div className="animate-spin rounded-full h-8 w-8 border-b-2 border-primary-600" /></div>)}
        {error && (<div className="absolute inset-0 z-10 flex items-center justify-center"><div className="text-red-500 font-medium">Error: {error.message}</div></div>)}
        <div className="overflow-x-auto"><table className="w-full"><thead><tr className="bg-[var(--bg-secondary)] border-b border-[var(--border-color)]"><th className="w-12 px-4 py-3"><input type="checkbox" checked={allSelected} onChange={handleSelectAll} className="w-4 h-4 rounded border-[var(--border-color)] text-primary-600 focus:ring-primary-500" /></th>{isCodeVisible && <th className="px-4 py-3 text-left text-xs font-bold uppercase tracking-wider text-[var(--text-muted)]">Code</th>}{isNameVisible && <th className="px-4 py-3 text-left text-xs font-bold uppercase tracking-wider text-[var(--text-muted)]">Name</th>}{isTypeVisible && <th className="px-4 py-3 text-left text-xs font-bold uppercase tracking-wider text-[var(--text-muted)]">Type</th>}<th className="px-4 py-3 text-right text-xs font-bold uppercase tracking-wider text-[var(--text-muted)]">Actions</th></tr></thead><tbody className="divide-y divide-[var(--border-color)]">{!isLoading && reasons.length === 0 && (<tr><td colSpan={visibleColCount} className="px-4 py-12 text-center text-[var(--text-muted)]">No reasons found.</td></tr>)}{reasons.map((item: any) => { const id = item.uuid ?? String(item.id); return (<tr key={id} className="group hover:bg-gray-50 dark:hover:bg-gray-700/50 transition-all duration-200 cursor-pointer"><td className="px-4 py-4 whitespace-nowrap"><input type="checkbox" checked={selectedRowKeys.includes(id)} onChange={() => handleSelectRow(id)} className="w-4 h-4 rounded border-[var(--border-color)] text-primary-600 focus:ring-primary-500" /></td>{isCodeVisible && <td className="px-4 py-4 whitespace-nowrap"><span className="text-sm font-mono text-[var(--text-secondary)]">{item?.code ?? ''}</span></td>}{isNameVisible && <td className="px-4 py-4 whitespace-nowrap"><span className="text-sm font-medium text-[var(--text-primary)]">{item?.name ?? ''}</span></td>}{isTypeVisible && <td className="px-4 py-4 whitespace-nowrap"><span className="text-sm text-[var(--text-secondary)]">{item?.type ?? ''}</span></td>}<td className="px-4 py-4 whitespace-nowrap"><div className="flex items-center justify-end gap-2"><button className="inline-flex items-center gap-1.5 px-3 py-1.5 text-xs font-semibold text-blue-700 bg-blue-50 dark:bg-blue-900/30 dark:text-blue-400 rounded-lg hover:bg-blue-100 dark:hover:bg-blue-900/50 transition-all duration-200 group-hover:shadow-md" onClick={() => handleEditClick(item)}><Pencil size={14} strokeWidth={2.5} /><span>Edit</span></button><button className="inline-flex items-center gap-1.5 px-3 py-1.5 text-xs font-semibold text-red-700 bg-red-50 dark:bg-red-900/30 dark:text-red-400 rounded-lg hover:bg-red-100 dark:hover:bg-red-900/50 transition-all duration-200 group-hover:shadow-md" onClick={() => handleDeleteWithConfirmation(id)}><Trash2 size={14} strokeWidth={2.5} /><span>Delete</span></button></div></td></tr>); })}</tbody></table></div>
        <Pagination currentPage={currentPage} totalPages={totalPages} total={total} perPage={perPage} onPageChange={setCurrentPage} onPerPageChange={setPerPage} hasLoaded={!!meta} />
      </div>
      <ReasonAdd isOpen={addDrawerOpen} onClose={handleDrawerClose} data={{ initialData: editingItem }} onEvent={handleReasonEvent} />
    </div>
  );
}
